# Dockerfile para o Kali Linux com Wireshark
FROM kalilinux/kali-rolling

LABEL maintainer="Kensei CyberSec Lab <info@kensei.com>"

RUN apt update && \
    apt upgrade -y && \
    apt install -y wireshark curl && \
    rm -rf /var/lib/apt/lists/*

# Usuário padrão é root, que é o padrão da imagem kali-rolling
WORKDIR /root

CMD ["/bin/bash"]