# Dockerfile para o lab CLI
FROM kalilinux/kali-rolling

# Comando para criar o diretório e o arquivo do desafio durante a construção da imagem
RUN mkdir -p /root/.diretorio_secreto && \
    echo "KenseiCyberSec{D3s4f10_CLI_C0nclu1d0!}" > /root/.diretorio_secreto/.segredo_dojo